In [1]:
import numpy as np

## 1.numpy.array生成的是固定类型(int，默认为float)的数组
### 1.1. 直接添加一个数组（只能为int或float类型）以生成numpy.array

In [2]:
np.array([1,4,5]) # 整型

array([1, 4, 5])

### 1.2. 创建值为0的数组/矩阵

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros(shape=(3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

###  1.3. 创建值为1的数组/矩阵

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 1.4. 创建特定值的数组/矩阵

In [8]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [9]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [10]:
np.full(shape=(3,5),fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### 1.5. arange生成等步长的数组

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

### 1.6. linspace生成等差数列

In [13]:
np.linspace(0, 10, 15) # 起始点为0,终止点为10（不包括），生成15个等差数列

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

## 2. random生成随机数

### 2.1.  randint生成随机整数的数组/矩阵

In [14]:
np.random.randint(0,10)

5

In [15]:
np.random.randint(0,10,10)

array([7, 4, 6, 4, 5, 4, 4, 1, 0, 6])

In [16]:
np.random.randint(0,10,size = (3,4))

array([[5, 8, 7, 3],
       [6, 7, 0, 6],
       [0, 1, 9, 4]])

### 2.2 . seed随机种子，使得生成的随机数组/矩阵一致

In [17]:
np.random.seed(12)

In [18]:
np.random.randint(0,10,(3,4))

array([[6, 1, 2, 3],
       [3, 0, 6, 1],
       [4, 5, 9, 2]])

In [19]:
np.random.seed(12)
np.random.randint(0,10,(3,4))

array([[6, 1, 2, 3],
       [3, 0, 6, 1],
       [4, 5, 9, 2]])

### 2.3. random.random生成0-1之间均匀分布的浮点数

In [20]:
np.random.random(10)

array([0.72595416, 0.37283446, 0.67599758, 0.98364716, 0.48153021,
       0.91253883, 0.18987634, 0.14797388, 0.90726736, 0.68432507])

In [21]:
np.random.random((3,4))

array([[0.95772873, 0.45605092, 0.56314114, 0.80126538],
       [0.94317762, 0.22335928, 0.70293978, 0.49994509],
       [0.20266072, 0.62936457, 0.14429873, 0.05295153]])

### 2.4 normal生成正态分布的数组/矩阵

In [22]:
np.random.normal(1,5)

1.594402766380906

In [23]:
np.random.normal(1,1,5) #生成均值为0,方差为1的十个数组

array([ 0.89105074,  1.12431394, -0.03467218,  2.86194108, -0.34626923])

In [24]:
np.random.normal(1,1,(3,4))

array([[ 0.08620932, -0.08023723,  1.24473064,  1.13554853],
       [-0.14786946,  1.23358559,  1.77621522,  0.42295285],
       [ 3.02427573, -0.67302387,  2.40709829,  1.00321688]])