In [1]:
import numpy as np
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 1. 基础属性
### 1.1. ndim查看数组维度

In [2]:
X.ndim

2

### 1.2. shape查看维度及每个维度的元素个数

In [3]:
X.shape

(3, 5)

### 1.3. size查看元素个数

In [4]:
X.size

15

## 2. numpy.array的数据访问

### 2.1. 以矩阵的访问为例

In [5]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
X[:2,:3]  #访问前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [7]:
X[:2,::2]  #访问前两行，步长为2

array([[0, 2, 4],
       [5, 7, 9]])

In [8]:
X[::-1,::-1]  #反转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [9]:
X[:,-1] #访问所有行的最后一列得到一维数组

array([ 4,  9, 14])

### 2.2. copy()操作

In [10]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
subX = X[:2,:3]
subX[0,0] = 100
subX,X
#上述操作说明无论是子矩阵还是原矩阵修改数据都会导致另外一方的数据修改

(array([[100,   1,   2],
        [  5,   6,   7]]),
 array([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]]))

In [12]:
subX[0,0] = 0  #还原
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
subX = X[:2,:3].copy()  #加.copy()后修改子矩阵就不会改变原矩阵的数值了
subX[0,0] = 100
subX,X

(array([[100,   1,   2],
        [  5,   6,   7]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

## 3. reshape将数组转换为矩阵

In [14]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.reshape(2, 5)  #把x转换为2 × 5的矩阵

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
x.reshape(1,10)  #把x从一维向量转换为1 × 10的二位矩阵(注意有了两个"]")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 3.1. 自动生成确定行/列数的矩阵

In [17]:
x.reshape(10,-1)  #不管有多少元素，只要求生成10行，列自动得出

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [18]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 4. 合并操作
### 4.1. concatenate()拼接

In [20]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
x

array([1, 2, 3])

In [21]:
y

array([3, 2, 1])

In [22]:
np.concatenate([x,y])  #将两个向量合并为一个向量

array([1, 2, 3, 3, 2, 1])

In [23]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
B = y.reshape(1,-1)  #把y从向量转换为数组进行操作

In [36]:
np.concatenate([A,B])  #默认axis=0(沿着行的方向合并)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1]])

In [41]:
C = np.random.randint(0,5,(2,3))  #生成一个2 × 3矩阵，取值在[0,5)区间上
C 

array([[1, 1, 2],
       [2, 1, 4]])

In [43]:
np.concatenate([A,C],axis = 1)  #A和C沿着列的方向合并

array([[1, 2, 3, 1, 1, 2],
       [4, 5, 6, 2, 1, 4]])

### 4.2. vstack() 竖着合并

In [44]:
np.vstack([A,C])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 2],
       [2, 1, 4]])

### 4.3. hstack() 横着合并

In [45]:
np.hstack([A,C])

array([[1, 2, 3, 1, 1, 2],
       [4, 5, 6, 2, 1, 4]])

## 5. 分割操作

In [49]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 5.1. split() 分割

In [51]:
x1, x2, x3 = np.split(x, [3, 5])

In [52]:
x1, x2, x3

(array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9]))

In [53]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.split(A, [2])  #默认沿着行的方向分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [56]:
np.split(A, [2], axis=1)  #沿着列的方向分割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### 5.2. vsplit() 竖着分割

In [57]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
upper, lower = np.vsplit(A,[2])

In [64]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 5.3. hsplit() 横着分割

In [66]:
left, right = np.hsplit(A,[2])

In [67]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [68]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [69]:
data, result = np.hsplit(A,[-1])

In [70]:
data

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [71]:
result

array([[ 3],
       [ 7],
       [11],
       [15]])