In [1]:
import numpy as np

In [2]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 1. Universal Functions(通用函数)

###  + - * / ** // % 

In [3]:
1 / X  #取倒数
np.abs(X)  #取绝对值
np.sin(X)  #取正弦函数
np.cos(X)  #取余弦函数
np.tan(X)  #取正切函数
np.exp(X)  #取e的X次方
np.power(3, X) #取3的X次方
np.log(X) #取以e为底X的对数
np.log2(X) #取以2为底X的对数
np.log10(X) #取以10为底X的对数

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 2. 矩阵运算

In [4]:
A = np.arange(4).reshape(2,2)
B = np.full((2,2),10)

In [5]:
A

array([[0, 1],
       [2, 3]])

In [6]:
B

array([[10, 10],
       [10, 10]])

In [7]:
A + B  #对应元素相加
A - B  #对应元素相减
A * B  #对应元素相乘
A.dot(B)  #做A矩阵与B矩阵相乘
A.T    #取A的转置

array([[0, 2],
       [1, 3]])

## 3. 向量和矩阵运算

In [8]:
v = np.array([1, 2])

In [9]:
A + v  #向量与矩阵的每一行做运算

array([[1, 3],
       [3, 5]])

In [10]:
np.tile(v, (2, 1))  #表示v在行向量上堆叠两次，在列向量上堆叠一次

array([[1, 2],
       [1, 2]])

In [11]:
v

array([1, 2])

In [12]:
A

array([[0, 1],
       [2, 3]])

In [13]:
v.dot(A)  #向量v与矩阵A相乘

array([4, 7])

In [14]:
A.dot(v)  #numpy自动将v从行向量变为列向量在做运算

array([2, 8])

## 4. 矩阵的逆

### 4.1. linalg.inv()求方阵的逆矩阵

In [15]:
A

array([[0, 1],
       [2, 3]])

In [16]:
invA = np.linalg.inv(A)  #得到A的逆矩阵(必须是方阵)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

### 4.2. linalg.pinv()求伪逆矩阵

In [17]:
X = np.arange(16).reshape(2, 8)  #生成一个2 × 8的矩阵
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
pinvX = np.linalg.pinv(X)  #变为一个8 × 2的矩阵
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -5.20417043e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [19]:
X.dot(pinvX)  #得到一个2 × 2的单位矩阵

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 6.66133815e-16,  1.00000000e+00]])