In [1]:
import numpy as np

In [2]:
X = np.random.normal(0, 1, size=100000)

## 1. arg索引

In [3]:
np.argmin(X)  #找出X中最小值的索引(即最小值在数组中的位置)

47430

In [4]:
X[57339] == np.min(X)

False

## 2. 排序和使用索引

### 2.1. 对数组的操作

In [5]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
np.random.shuffle(x)  #乱序
x

array([12,  8,  9,  0,  5,  4,  7, 15, 13, 11, 10, 14,  6,  2,  3,  1])

In [7]:
np.sort(x)  #返回排好序的x,但是x本身还是乱序的，想把x排序需要用x.sort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
np.partition(x, 3)  #对于乱序后的数组，比3小的在左边，比3大的在右边

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 11, 10,  6, 12, 14, 13, 15])

In [9]:
np.argpartition(x, 3)  #查看的是索引

array([ 3, 15, 13, 14,  5,  4,  6,  1,  2,  9, 10, 12,  0, 11,  8,  7])

### 2.2. 对矩阵的操作

In [10]:
X = np.random.randint(10, size=(4,4))
X

array([[5, 2, 3, 3],
       [8, 7, 8, 5],
       [5, 1, 2, 0],
       [4, 1, 0, 0]])

In [11]:
np.sort(X)  #默认 axis=1 每行排序

array([[2, 3, 3, 5],
       [5, 7, 8, 8],
       [0, 1, 2, 5],
       [0, 0, 1, 4]])

In [12]:
np.sort(X, axis=0)  #按列排序

array([[4, 1, 0, 0],
       [5, 1, 2, 0],
       [5, 2, 3, 3],
       [8, 7, 8, 5]])