In [3]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 1. 获取数组/矩阵中的值

### 1.1. 获取x中的值

In [5]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0, 2],
                [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

### 1.2. 获取X中的值

### 1.2.1. 获取索引为01,12,23的值

In [9]:
rol = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[rol, col]                 

array([ 1,  6, 11])

### 1.2.2. 得到前两行，索引为1,2,3列的值

In [10]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

### 1.2.3. 传入布尔数组获取值

In [13]:
col = [True, False, True, True]
X[1:3, col]    #获取的是23行，134列的值

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## 2. numpy.array的比较

### 2.1. 对数组/矩阵使用比较运算符，返回boolean类型的值

In [14]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [15]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 2.2.求和及判断

### 2.2.1. sum()求满足条件的和

In [25]:
np.sum(x <= 3)

4

In [26]:
np.sum(X % 2 == 0, axis=1) #沿着列的方向，即看每一行有多少偶数

array([2, 2, 2, 2])

In [28]:
np.sum(X % 2 == 0, axis=0) #沿着行的方向，即看每一列有多少偶数

array([4, 0, 4, 0])

In [29]:
np.sum((x > 3) & (x < 10))  #与运算

6

In [30]:
np.sum((x % 2 == 0) | (x > 10))  #或运算

11

In [31]:
np.sum(~(x == 0)) # 非运算

15

### 2.2.2 count_nonzero()求非0元素的个数

In [20]:
np.count_nonzero(x <= 3)  #因为x<=3返回的是布尔型，True代表1/False代表0

4

### 2.2.3.  any()判断是否有元素满足条件(返回的是布尔型)

In [21]:
np.any(x == 0)

True

In [22]:
np.any(x < 0)

False

### 2.2.4. all()判断所有元素是否满足条件(返回的是布尔型)

In [23]:
np.all(x >= 0)

True

In [24]:
np.all(x > 0)

False

### 2.2.5. 例：每一行最后的特征值能被3整除的行

In [32]:
X[X[:, -1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])